print ("          请输入以下信息生成您的简历")
name=input("您的姓名:")
gender=input("您的姓别:")
age=input("您的年龄:")
school=input("您的毕业学校:")
major=input("您的专业:")
print("*"*10)
print("                    个人简历")
print("   姓名:"+name)
print("   姓别:"+gender)
print("   年龄:"+age)
print("   学校:"+school)
print("   专业:"+major)